import { useState } from "react";

export default function LetterPreview({ letter, loading, error, source, candidateName, role }) {
  const [copied, setCopied] = useState(false);

  async function handleCopy() {
    if (!letter) return;
    try {
      await navigator.clipboard.writeText(letter);
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch {
      
    }
  }

  const today = new Date().toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <div className="letter-stage">
      <div className="letter-paper">
        {loading && (
          <div className="letter-loading">
            <div className="nib">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
                <path d="M3 21l3-1 11-11a2.1 2.1 0 0 0-3-3L3 17l-1 3 1 1z" />
                <path d="M14 6l3 3" />
              </svg>
            </div>
            <div className="ink-line" />
            <p className="caption">Drafting your letter…</p>
          </div>
        )}

        {!loading && !letter && !error && (
          <div className="letter-empty">
            <div className="envelope" />
            <p className="eyebrow">Nothing drafted yet</p>
            <p>Fill in the details on the left and your cover letter will appear here, ready to copy.</p>
          </div>
        )}

        {!loading && error && (
          <div className="letter-empty">
            <div className="envelope" />
            <p className="eyebrow" style={{ color: "var(--wax)" }}>Could not generate</p>
            <p>{error}</p>
          </div>
        )}

        {!loading && letter && !error && (
          <>
            <div className="seal">
              <span>Drafted</span>
            </div>
            <div className="letter-head">
              <div className="from">
                <h2>{candidateName || "Your Name"}</h2>
                <div className="role">{role || "Candidate"}</div>
              </div>
              <div className="date">{today}</div>
            </div>
            <div className="letter-body">{letter}</div>
            <div className="letter-foot">
              <span className={`source-tag${source === "ai" ? " ai" : ""}`}>
                {source === "ai" ? "● Generated by LLM" : "○ Quick-draft template"}
              </span>
              <button className={`copy-btn${copied ? " copied" : ""}`} onClick={handleCopy}>
                {copied ? "Copied" : "Copy to clipboard"}
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
